[package]
name = "webauthn"
type = "lib"
authors = ["Oleh Misarosh <olehmisar@gmail.com"]
compiler_version = ">=0.34.0"

[dependencies]
base64 = { git = "https://github.com/olehmisar/noir_base64/", tag = "v0.3.0" }
